name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [main]  # ou 'master' selon ton dépôt

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: withastro/action@v2
        with:
          path: ./
          deploy_dir: ./dist
          branch: gh-pages
